# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Redcroas, Airbnb]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username smithla2159
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username amore 
issuehunt: # Replace with a single IssueHunt username de ray
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://ulta.com','https://en.m.wikipedia.org/wiki/Sic','https://taxfoundation.org/case-for-universal-savings-accounts/','https://www.denverpost.com/2007/05/10/yahweh-led-violent-religious-sect/','https://www.npr.org/2021/07/01/1012388865/boy-scouts-of-america-settlement-with-sexual-abuse-survivors-victims','https://hunters.Io','https://bitbucket.org/Mouse33583/curl-docker/','https://www.thebanker.com/Information/Services/The-Banker-Database','https://royalseeds.con','https://www.politico.com/news/agenda/2021/07/30/with-the-eviction-moratorium-ending-its-time-to-focus-on-landlords-501785','https://hellored.org','https://ec.europa.eu/eurostat/documents/2995521/9618249/1-26022019-AP-EN.pdf/f765d183-c3d2-4e2f-9256-cc6665909c80','https://wikileaks.org/plusd/cables/08NAPLES96_a.html', 'https://homedepot.com']
