# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [NAPA, REDBULL]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username amore 
issuehunt: # Replace with a single IssueHunt username de ray
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://ulta.com','https://en.m.wikipedia.org/wiki/Sic','https://taxfoundation.org/case-for-universal-savings-accounts/','https://www.denverpost.com/2007/05/10/yahweh-led-violent-religious-sect/','https://www.npr.org/2021/07/01/1012388865/boy-scouts-of-america-settlement-with-sexual-abuse-survivors-victims','https://hunters.Io','https://'https://pornhub.com', 'https://homedepot.com']
